-- Production PostgreSQL migration for PR3 home scheduler items.

CREATE TABLE IF NOT EXISTS schedule_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    lecture_id BIGINT NULL,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(200) NOT NULL,
    memo VARCHAR(2000) NULL,
    due_at TIMESTAMPTZ NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_schedule_item_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_schedule_item_lecture FOREIGN KEY (lecture_id) REFERENCES lecture (id)
);

CREATE INDEX IF NOT EXISTS idx_schedule_item_member_due
    ON schedule_item (member_id, due_at);

CREATE INDEX IF NOT EXISTS idx_schedule_item_member_completed
    ON schedule_item (member_id, completed);
